services:
  web:
    build: .
    container_name: tutorias_web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=tutorias_db
      - DB_USER=tutorias_user
      - DB_PASS=12345
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: tutorias_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tutorias_db
      MYSQL_USER: tutorias_user
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./database/migration_permisos.sql:/docker-entrypoint-initdb.d/02_migration_permisos.sql
      - ./database/seed_carreras_materias_horarios.sql:/docker-entrypoint-initdb.d/03_seed_carreras_materias_horarios.sql
      - ./database/migrations/gestion_cupos_periodos.sql:/docker-entrypoint-initdb.d/04_gestion_cupos_periodos.sql
      - ./database/migrations/05_notificaciones.sql:/docker-entrypoint-initdb.d/05_notificaciones.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tutorias_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - db

volumes:
  mysql_data:
